### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Subucc** [darkarp/malkit#1]
Hello, when I put command: git clone https://github.com/darkarp/malkit.git  in powershel, i'm getting an error: 
git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the s
pelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ git clone https://github.com/darkarp/malkit.git
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Subucc** [comment]
Nevemind, i only had to download "git" program

**Comment by ariandexapy** [comment]
😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂

**Comment by darkarp** [comment]
😂

But regardless, just for your information, this project is likely not working at all. A complete rework is in the process of being made which will improve and turn this into a good project.
